### ISSUE TITLE
LIFX does not setup correctly

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#195]
This error takes place rarely on home assistant.
Usually after many home assistant application restart.
It can be solved with a raspberry pi reboot but the root cause has not been analysed yet.

Home Assistant version:
0.46.0

Component:
Lifx_legacy

Traceback:
```
Traceback:
2017-06-16 09:09:48 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform lifx_legacy
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 160, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/light/lifx_legacy.py", line 55, in setup_platform
    lifx_library = LIFX(add_devices, server_addr, broadcast_addr)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/light/lifx_legacy.py", line 77, in __init__
    broadcast_addr)
  File "/home/homeassistant/.homeassistant/deps/liffylights.py", line 100, in __init__
    self._sock.bind((listener_addr, UDP_PORT))
OSError: [Errno 98] Address already in use 
```

**Comment by commento** [comment]
probably related to a pending connection to the connection and a wrong HA restart.
I have added a socket option that should handle this scenario.
```
setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

before socket bind in File "/home/homeassistant/.homeassistant/deps/liffylights.py", line 100
I will verify if it occurs again.
