### ISSUE TITLE
Slack component issue at startup

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#197]
This error takes place sometime in home assistant.
It can be solved with a home assistant restart but the root cause has not been analysed yet.

Home Assistant version:
0.46.0

Component:
slack based on notify

Traceback:
```
2017-06-26 11:58:43 ERROR (MainThread) [homeassistant.components.notify] Error setting up platform slack
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
    File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x6b9e2750>: Failed to establish a new connection: $

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/auth.test?token=xoxp-3151015473-17419423954$

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/notify/__init__.py", line 101, in async_setup_platform
    platform.get_service, hass, p_config, discovery_info)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/notify/slack.py", line 41, in get_service
    config.get(CONF_ICON, None))
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/notify/slack.py", line 64, in __init__
    self.slack.auth.test()
  File "/home/homeassistant/.homeassistant/deps/slacker/__init__.py", line 110, in test
    return self.get('auth.test')
  File "/home/homeassistant/.homeassistant/deps/slacker/__init__.py", line 90, in get
    api, **kwargs
  File "/home/homeassistant/.homeassistant/deps/slacker/__init__.py", line 66, in _request
    **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
    File "/srv/homeassistant/lib/python3.4/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/auth.test?token=xoxp-3151015473-174194239540-177395922881-$
2017-06-26 11:58:43 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 41.7 seconds.
2017-06-26 11:58:43 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=notify>
```

**Comment by adamja** [comment]
@commento I had this same error and discovered my pi didn't have an internet connection which is more than likely the cause for me. Did you resolve it?
