### ISSUE TITLE
HUE bridge connection error on NUIMO APP

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#262]
Error occurring often when Philips hue component is active. 
Correct behaviour is restored moving to another component and returning to the Philips hue component.
To be handled correctly.
`2017-08-04 08:58:51,066 ERROR [senic_hub.nuimo_app.components] [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/root/senic-hub/senic_hub/nuimo_app/components/__init__.py", line 53, in _run
    self.run()
  File "/home/root/senic-hub/senic_hub/nuimo_app/components/philips_hue.py", line 330, in run
    self.lights.update_state()
  File "/home/root/senic-hub/senic_hub/nuimo_app/components/philips_hue.py", line 162, in update_state
    response = self.bridge.get_light()
  File "/usr/lib/python3.5/site-packages/phue.py", line 846, in get_light
    return self.request('GET', '/api/' + self.username + '/lights/')
  File "/usr/lib/python3.5/site-packages/phue.py", line 663, in request
    result = connection.getresponse()
  File "/usr/lib/python3.5/site-packages/raven/breadcrumbs.py", line 346, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by commento** [comment]
as reported in #263 the connection loss issue has to be handled properly for both philips hue and sonos components in order to cover all the edge cases. This specific issue (reported above) has been fixed with the workaround merged in the related PR.
