### ISSUE TITLE
Error while device discovery

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#335]
The unexpected behaviour takes place during device discovery.
The UI shows a throbber for a long time. After a while, the device list appears.
It happens rarely but all the exceptions have to be handled correctly.
```
2017-10-06 09:18:15,616 WARNI [netdisco.ssdp] Error fetching description at http://192.168.1.51:1400/xml/device_description.xml
2017-10-06 09:18:15,955 WARNI [netdisco.ssdp] Found malformed XML at http://192.168.1.8:2869/upnphost/udhisapi.dll?content=uuid:ade7e5de-6475-4210-9560-15012dd35ec5:



Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0xb2f7a5b0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.51', port=1400): Max retries exceeded with url: /xml/device_description.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xb2f7a5b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/device_discovery", line 9, in <module>
    load_entry_point('senic-hub', 'console_scripts', 'device_discovery')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/root/senic-hub/senic_hub/backend/device_discovery.py", line 60, in command
    discover_and_merge_devices(devices_path, now)
  File "/home/root/senic-hub/senic_hub/backend/device_discovery.py", line 68, in discover_and_merge_devices
    discovered_devices = discover_devices()
  File "/home/root/senic-hub/senic_hub/backend/device_discovery.py", line 103, in discover_devices
    device_description = get_device_description(device_type, device_info)
  File "/home/root/senic-hub/senic_hub/backend/device_discovery.py", line 200, in get_device_description
    return device_class(device_info).device_description
  File "/home/root/senic-hub/senic_hub/backend/device_discovery.py", line 316, in __init__
    response = requests.get('http://{}:1400/xml/device_description.xml'.format(self.ip_address))
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.51', port=1400): Max retries exceeded with url: /xml/device_description.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xb2f7a5b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/netdisco/mdns.py", line 20, in start
    self.zeroconf = zeroconf.Zeroconf()
  File "/usr/lib/python3.5/site-packages/zeroconf.py", line 1523, in __init__
    socket.inet_aton(_MDNS_ADDR) + socket.inet_aton(i))
OSError: [Errno 105] No buffer space available

2017-10-06 09:20:47,768 INFO  [root] Next device discovery run scheduled for 2017-10-06 09:20:55.771880
```

**Comment by neelotpalnag** [comment]
Will be closed by a PR in the senic-os repository. This error has been fixed by updating the `sysctl` value : `/proc/sys/net/ipv4/igmp_max_memberships` to more than zero.
