### ISSUE TITLE
sonos traceback errors in nuimo_app

### ISSUE THREAD

**Issue by commento** [getsenic/senic-hub#340]
I noticed that these errors were not present with the m1 board was used, but this is just a speculation to be verified.

**EDIT:**
it has been verified that the issue is present only on the nano pi neo and not in the M1,
so the issue is platform specific

- first error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/soco/events.py", line 225, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
```

- second error:
```
2017-10-10 09:19:04,298 ERROR [soco.services] UPnP Error 701 received: Transition not available from 192.168.1.78
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/lib/python3.5/site-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.1.78
```

**Comment by juergenschubert** [comment]
I do have this kind of exception error for one sonos on my raspberry PI 3

Dec 18 12:26:52 hassbian hass[1964]: ----------------------------------------
Dec 18 12:26:52 hassbian hass[1964]: Exception happened during processing of request from ('192.168.1.113', 49464)
Dec 18 12:26:52 hassbian hass[1964]: Traceback (most recent call last):
Dec 18 12:26:52 hassbian hass[1964]:   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
Dec 18 12:26:52 hassbian hass[1964]:     self.finish_request(request, client_address)
Dec 18 12:26:52 hassbian hass[1964]:   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
Dec 18 12:26:52 hassbian hass[1964]:     self.RequestHandlerClass(request, client_address, self)
Dec 18 12:26:52 hassbian hass[1964]:   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
Dec 18 12:26:52 hassbian hass[1964]:     self.handle()
Dec 18 12:26:52 hassbian hass[1964]:   File "/usr/lib/python3.5/http/server.py", line 422, in handle
Dec 18 12:26:52 hassbian hass[1964]:     self.handle_one_request()
Dec 18 12:26:52 hassbian hass[1964]:   File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
Dec 18 12:26:52 hassbian hass[1964]:     method()
Dec 18 12:26:52 hassbian hass[1964]:   File "/srv/homeassistant/lib/python3.5/site-packages/soco/events.py", line 233, in do_NOTIFY
Dec 18 12:26:52 hassbian hass[1964]:     variables = parse_event_xml(content)
Dec 18 12:26:52 hassbian hass[1964]:   File "/srv/homeassistant/lib/python3.5/site-packages/soco/events.py", line 134, in parse_event_xml
Dec 18 12:26:52 hassbian hass[1964]:     value = from_didl_string(value)[0]
Dec 18 12:26:52 hassbian hass[1964]:   File "/srv/homeassistant/lib/python3.5/site-packages/soco/data_structures_entry.py", line 52, in from_didl_string
Dec 18 12:26:52 hassbian hass[1964]:     item = cls.from_element(elt)
Dec 18 12:26:52 hassbian hass[1964]:   File "/srv/homeassistant/lib/python3.5/site-packages/soco/data_structures.py", line 467, in from_element
Dec 18 12:26:52 hassbian hass[1964]:     raise DIDLMetadataError("Missing restricted attribute")
Dec 18 12:26:52 hassbian hass[1964]: soco.exceptions.DIDLMetadataError: Missing restricted attribute
Dec 18 12:26:52 hassbian hass[1964]: ----------------------------------------
