### ISSUE TITLE
ValueError - 'Fernet Key' while reading configuration files

### ISSUE THREAD

**Issue by neelotpalnag** [getsenic/senic-hub#359]
I have encountered this issue occasionally on many devices: 

`Traceback (most recent call last):
  File "/usr/bin/device_discovery", line 9, in <module>
    load_entry_point('senic-hub==0.1.2', 'console_scripts', 'device_discovery')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/senic_hub/backend/device_discovery.py", line 45, in command
    app = get_app(abspath(config), name='senic_hub')
  File "/usr/lib/python3.5/site-packages/pyramid/paster.py", line 31, in get_app
    global_conf=options)
  File "/usr/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python3.5/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  **File "/usr/lib/python3.5/site-packages/senic_hub/backend/__init__.py", line 9, in main
    config = configure(global_config, **settings)
  File "/usr/lib/python3.5/site-packages/senic_hub/backend/config.py", line 27, in configure
    config.registry.crypto_settings = crypto_settings(global_config, **settings)**
  File "/usr/lib/python3.5/site-packages/senic_hub/backend/config.py", line 51, in crypto_settings
    return CryptoYAML(settings_datafile, keyfile=settings_keyfile)
  File "/usr/lib/python3.5/site-packages/cryptoyaml/api.py", line 55, in __init__
    self.fernet = Fernet(self.key)
  File "/usr/lib/python3.5/site-packages/cryptography/fernet.py", line 37, in __init__
    "Fernet key must be 32 url-safe base64-encoded bytes."
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.`

Has anyone ever encountered the same, or knows a first-view-solution to this? 
@kelada @commento @rudolfs

**Comment by commento** [comment]
can you explain a little bit more about the context? (which procedure? which app?) 
anyway, I never saw this error

**Comment by neelotpalnag** [comment]
It occurs whenever a configuration file is being open. **ValueError: Fernet key must be 32 url-safe base64-encoded bytes.** . 
It comes up very very rarely, but it kills the `senic_hub, nuimo_app, device_discovery` processes

**Comment by neelotpalnag** [comment]
Felix's SD Card logs are full of this error in all the above corresp. logs

**Comment by neelotpalnag** [comment]
[senic_hub.log](https://github.com/getsenic/senic-hub/files/1398586/senic_hub.log)

**Comment by commento** [comment]
maybe for alpha testers would be better to have also info logs activated otherwise it's much harder to find issues root causes

**Comment by TheMeaningfulEngineer** [comment]
Checked the code where the error occurs: `/usr/lib/python3.5/site-packages/cryptography/fernet.py", line 38`

When the issue occurs there isn't a key present:

```
class Fernet(object):
    def __init__(self, key, backend=None):
        if backend is None:
            backend = default_backend()

        key = base64.urlsafe_b64decode(key)
        print("###### ALAN DEBUG. FERNET KEY:" + str(key))
        if len(key) != 32:
            raise ValueError(
                "Fernet key must be 32 url-safe base64-encoded bytes."
            )
```
Output:  `###### ALAN DEBUG. FERNET KEY:b''`

**Comment by TheMeaningfulEngineer** [comment]
Found some Senic code that seems to be related to keys/crypto topics:

https://github.com/getsenic/senic-hub/blob/master/senic_hub/backend/config.py#L32

**Comment by TheMeaningfulEngineer** [comment]
Seems to happen after a senic_hub_factory_reset followed by a hard reset.
