### ISSUE TITLE
Creating a Hue group no longer works

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-hub#361]
The current configuration is 6 lights (2 colour, 2 ambiance, 2 white), they are each in 3 rooms (Party Room, Ambiance Room, Living Room) -- configured via the Philips Hue App.

When pressing "Add another App" and selecting the Philips Hue bridge nothing happens.

Looking at the `senic_hub.log` file the following error is thrown:
```
2017-10-25 12:49:58,695 ERROR [waitress] Exception when serving /-/nuimos/c7-de-b3-28-ad-b7/components
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python3.5/site-packages/raven/middleware.py", line 98, in __call__
    iterable = self.application(environ, start_response)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python3.5/site-packages/pyramid/tweens.py", line 51, in excview_tween
    request_iface=request_iface.combined
  File "/usr/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/usr/lib/python3.5/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/usr/lib/python3.5/site-packages/cornice/service.py", line 493, in wrapper
    response = view_(request)
  File "/home/root/senic-hub/senic_hub/backend/views/nuimo_components.py", line 115, in add_nuimo_component_view
    component = create_component(device)
  File "/home/root/senic-hub/senic_hub/backend/views/nuimo_components.py", line 168, in create_component
    light_ids = sorted(list(device['extra']['lights']))
KeyError: 'lights'
```

Additional, when logging the contents of the dictionary `device['extra']` is shows that `username: None`. It is unclear to me why this issue only started showing up today after I changed the configuration of the Philips Hue lights.

**Comment by commento** [comment]
the PR #362 introduces a check on the request format but the error has to be solved in the frontend, in particular:
https://github.com/getsenic/senic-home-automation-app/blob/master/app/screens/hub/devices/HubDevicesAddComponentScreen.js
Where the fetchDevices() has to filter only the authenticated devices.

**Comment by neelotpalnag** [comment]
@kelada : Is this resolved in the frontend ?

**Comment by kelada** [comment]
@neelotpalnag this was fixed in the ``dev`` branch and has yet to be merged into ``master``.
