### ISSUE TITLE
Detecting the correct hci

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-hub#392]
The new BT module sometimes causes the following error:

```
==> /data/senic-hub/logs/bluenet.log <==
2018-01-08 11:12:10,346 INFO  [senic_hub.bluenet.bluez_peripheral] Disabling BR/EDR...
Traceback (most recent call last):
  File "/usr/bin/bluenet", line 11, in <module>
    load_entry_point('senic-hub==0.2.248+8123a2b', 'console_scripts', 'bluenet')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/senic_hub/bluenet/bluenet.py", line 53, in bluenet_start
    ctx.obj.run(hostname, alias, auto_advertise)
  File "/usr/lib/python3.5/site-packages/senic_hub/bluenet/bluenet.py", line 107, in run
    self._ble_peripheral = Peripheral(bluetooth_alias, self._bluetooth_adapter)
  File "/usr/lib/python3.5/site-packages/senic_hub/bluenet/bluez_peripheral.py", line 53, in __init__
    self._disable_br_edr()
  File "/usr/lib/python3.5/site-packages/senic_hub/bluenet/bluez_peripheral.py", line 286, in _disable_br_edr
    was_powered = self.is_powered
  File "/usr/lib/python3.5/site-packages/senic_hub/bluenet/bluez_peripheral.py", line 192, in is_powered
    return self._adapter_props.Get('org.bluez.Adapter1', 'Powered') == 1
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
```

The adapter is detected as hci1:
```
busctl tree org.bluez
└─/org
  └─/org/bluez
    └─/org/bluez/hci1
```

Bluenet is started with a hardcoded `hci0` 
```
# cat /etc/supervisor/conf.d/bluenet.conf
[program:bluenet]
command = /usr/bin/bluenet -b hci0 -w wlan0 start -v -h http://%%IP:6543/-/ -a 'Senic Hub'
autostart=false
autorestart=true
```

Manually changing that fixes the issue.

# Suggested solution

Ideally, the controller would be always detected by the kernel under the same name.
A simple way how to enforce it [wasn't identified](https://unix.stackexchange.com/questions/410449/consistent-enumeration-of-a-btattached-controller) so the quickest path is to approach
it in userspace.

**Comment by avichalp** [comment]
Thanks for suggesting this solution. 
It seems like a function for finding adapter is already implemented here: 
https://github.com/getsenic/senic-hub/blob/master/senic_hub/bluenet/bluez_peripheral.py#L137-L164

This is called when `Peripheral` class is instantiated without adapter or `adapter=None`.
So we should change the way we call`Peripheral()` class in bluenet.py to pass to make `self._bluetooth_adapter = None`
https://github.com/getsenic/senic-hub/blob/master/senic_hub/bluenet/bluenet.py#L107

and for that we need to update `bluenet_cli` function in the bluenet.py file something like:
```
 def bluenet_cli(ctx, wlan, bluetooth):
     if not wlan:
         wlan = 'wlan0'        
     if not bluetooth:
         bluetooth = None
     ctx.obj = BluenetDaemon(wlan, bluetooth)
```

https://github.com/getsenic/senic-hub/blob/master/senic_hub/bluenet/bluenet.py#L33-L36

Now if we avoid passing `-b` flag to bluenet process this should find adapter on it own.

**Comment by TheMeaningfulEngineer** [comment]
Tested, this seems to be working correctly. Bravo :)

Would omit this part:
```
 not bluetooth:
         bluetooth = None
```
Seems to be somewhat redundant.

Hm...
To solve this issues a pull request an another repository needs to be made. 
[This](https://github.com/getsenic/senic-os/blob/master/meta-senic/recipes-hub/hub-configuration/files/supervisor_bluenet.conf) is the file responsible for the hardcoding of the `hci0`.
It's in the repository that builds the complete image.

Can you pls make the pull request with that change on that repo, cross referencing the
issue and pull request in the comments or descriptions.
Once you're done assign me to the pull request, I'll test it, reconfirm that it solves
the issue and merge.

**Comment by avichalp** [comment]
Here is the PR: https://github.com/getsenic/senic-os/pull/75

**Comment by TheMeaningfulEngineer** [comment]
Solved with the above PR
