### ISSUE TITLE
`KeyError: 'formatters'` when starting netwatch

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/senic-hub#404]
```
==> /data/senic-hub/logs/netwatch.log <==                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                          
  File "/usr/bin/netwatch", line 11, in <module>                                                                                                                                                            
    load_entry_point('senic-hub', 'console_scripts', 'netwatch')()                                                                                                                                          
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point                                                                                                          
    return get_distribution(dist).load_entry_point(group, name)                                                                                                                                             
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point                                                                                                         
    return ep.load()                                                                                                                                                                                        
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2316, in load                                                                                                                     
    return self.resolve()                                                                                                                                                                                   
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2322, in resolve                                                                                                                  
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/root/senic-hub/senic_hub/backend/netwatch.py", line 23, in <module>
    'etc/senic_hub.ini', disable_existing_loggers=False
  File "/usr/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

Seems to be dying here:

https://github.com/getsenic/senic-hub/blob/improve-logging/senic_hub/backend/netwatch.py#L23

**Comment by avichalp** [comment]
Here is the fix for this: https://github.com/getsenic/senic-hub/pull/402
I was caused because of wrong path to conf file.
